# Generated by Django 3.0.5 on 2020-06-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0004_auto_20200429_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('name', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('position', models.TextField(blank=True, null=True)),
                ('affiliation', models.TextField(blank=True, db_column='Affiliation', null=True)),
                ('about_field', models.TextField(blank=True, db_column='about ', null=True)),
                ('webpage', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('twitter', models.TextField(blank=True, null=True)),
                ('img', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'about',
                'managed': False,
            },
        ),
    ]
