# Generated by Django 3.0.5 on 2022-02-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0006_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('ID', models.TextField(blank=True, db_column='ID', primary_key=True, serialize=False)),
                ('Name', models.TextField(blank=True, db_column='Name', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
