# Generated by Django 3.0.5 on 2022-02-16 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0008_auto_20220216_0331'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='description',
            table='website_parameters',
        ),
    ]
